version: "3"

services:

  microwebservices-varnish:
    build: ./images/microwebservices-varnish/
    image: microwebservices-varnish:7.0.2
    container_name: microwebservices-varnish
    restart: unless-stopped
    ports:
      - ${MICROWEBSERVICE_VARNISH_HTTP_PORT}:80
    environment:
      VARNISH_STORAGE_BACKEND: "file,/var/lib/varnish/file-cache.bin,50G"
    depends_on:
      - microwebservices-api

  microwebservices-api:
    build: ./images/microwebservices-api/
    image: microwebservices-api:0.0.1-SNAPSHOT
    container_name: microwebservices-api
    restart: unless-stopped
    ports:
      - ${MICROWEBSERVICE_HTTP_PORT}:8080

  bacon-cache-warmer:
    image: abesesr/bacon-cache-warmer:1.3.0
    container_name: bacon-cache-warmer
    restart: unless-stopped
    environment:
      BACON_RSS_URL: ${BACON_RSS_URL}
      BACON_MAX_URL_TO_WARM: ${BACON_MAX_URL_TO_WARM}
      BACON_DELAY_BETWEEN_WARM: ${BACON_DELAY_BETWEEN_WARM}
      BACON_CACHEWARMER_CRON: ${BACON_CACHEWARMER_CRON}
      BACON_CACHEWARMER_RUN_AT_STARTUP: ${BACON_CACHEWARMER_RUN_AT_STARTUP}
      BACON_CACHEWARMER_JUST_ONCE: ${BACON_CACHEWARMER_JUST_ONCE}
      # SED pour tout chauffer
      #BACON_URL_SED_BEFORE_WARM: 's#http://bacon.abes.fr/package2kbart/\(.*\)#http://microwebservices-varnish:80/MicroWebServices/?servicekey=bacon_pck2kbart\&para1=\1\&para2=\1\&para3=\1\&format=application/vnd.ms-excel#g'
      # SED pour chauffer que les KBART non datés
      BACON_URL_SED_BEFORE_WARM: 's#http://bacon.abes.fr/package2kbart/\([A-Z_\-]\+\)\(_[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\)#http://microwebservices-varnish:80/MicroWebServices/?servicekey=bacon_pck2kbart\&para1=\1\&para2=\1\&para3=\1\&format=application/vnd.ms-excel#g'
    depends_on:
      - microwebservices-varnish

